### PR TITLE
Fix UI when new ruleset created and viewed

### LINKED ISSUE #340: Ruleset Editor Blank Values on Initial Ruleset creation
When first entering the ruleset editor, if you create a new ruleset that has another existing ruleset as it's parent, all of the editors are active, and their values are blank (as if you had created a new ruleset without a parent).

Additionally, once an existing ruleset has been opened, the ruleset editor exhibits the correct behavior upon creating a ruleset (all values populated, all editor check boxes are not checked).

### PR DESCRIPTION
**Pull request by brian-brazil**
Fixes #340

Simplify and cleanup code.

### CODE REVIEW

File: html/controls/rulesets.js [hunk 1]
```diff
@@ -1,15 +1,15 @@
-initialize();
 var rulesets = {};
+var activeRuleset = null;
 var definitions = {};
-var knownRulesets = {};
+initialize();
 
 function loadRulesets(displayId) {
```
Comment (frank-weinberg) [inline html/controls/rulesets.js]: The parameter is now unused

Comment (brian-brazil) [reply html/controls/rulesets.js]: Fixed
