### PR TITLE
Fix potential freeze & improve debug capabilities

### LINKED ISSUE #929: [BUG] All operator buttons (Start Jam / Stop / Timeout) become unresponsive after Undo
## Describe the bug

After pressing the **Undo** button during or between jams, all operator control
buttons — Start Jam, Stop Jam/TO, and Timeout — become permanently unresponsive
for the rest of the session. The scoreboard UI continues to load and display
correctly, but no jam can be started and no timeout can be called. The only
recovery is a full application restart.

The root cause is that `restoreSnapshot()` in `GameImpl.java` sets a guard flag
`restoreRunning = true` at the start of the restore operation but only clears it
back to `false` on the normal happy-path exit. If any exception is thrown during
the restore — for example due to the box trip snapshot reordering introduced in
commit `ebb90645` — the flag is never cleared and permanently blocks the three
button handlers:

```java
// startJam() — GameImpl.java
if (!isInJam() && !restoreRunning && !isOfficialScore() && ...) { ... }

// stopJamTO() — GameImpl.java
if ((...) && !restoreRunning && !isOfficialScore() && ...) { ... }

// timeout() — GameImpl.java
if (!restoreRunning && !isOfficialScore() && ...) { ... }
```

## To Reproduce

Steps to reproduce the behaviour:

1. Start the scoreboard (v2025.8 or v2025.9).
2. Start a new game.
3. Start the period clock (click **Start**).
4. Start a jam (click **Start**).
5. While the jam is running, press **Undo**.
6. Observe: the scoreboard reverts state, as expected.
7. Now attempt to press **Start Jam** again.
8. **Nothing happens** — the button fires but the jam does not start.
9. Attempt **Timeout** — also has no effect.
10. Attempt **Stop** — also has no effect.
11. All three buttons remain permanently unresponsive until the application is
    fully restarted.

Alternatively: the issue can be triggered more reliably by performing an Undo
when a skater has an active box trip (penalty box entry recorded), which causes
the box trip snapshot restoration path introduced in `ebb90645` to throw.

## Expected behaviour

After an Undo, the scoreboard should return to the previous state and all
operator buttons should remain fully functional. `restoreRunning` must be
guaranteed to return to `false` regardless of whether the restore succeeds or
fails.

## Root Cause Analysis

Two commits introduced between v2025.7 and v2025.8 interact to cause this:

**Commit `58904866`** — "protect against overwriting snapshots during a restore"

Introduced the `restoreRunning` boolean flag and added it as a guard to
`startJam()`, `stopJamTO()`, and `timeout()`. The flag is set to `true` at the
start of `restoreSnapshot()` and reset to `false` at the end, but with **no
`try/finally` protection**:

```java
protected void restoreSnapshot() {
    restoreRunning = true;
    // ... many operations ...
    restoreRunning = false; // never reached if an exception is thrown
}
```

**Commit `ebb90645`** — "fix box trip handling on undo"

Rewired the order of operations inside `restoreSnapshot()`, adding a second
box-trip restore loop and moving clock/state restoration earlier. This increased
the number of operations that run while `restoreRunning = true`, widening the
window in which an exception leaves the flag permanently set.

## Proposed Fix

Wrap the body of `restoreSnapshot()` in a `try/finally` block to guarantee the
flag is always cleared:

```java
protected void restoreSnapshot() {
    restoreRunning = true;
    try {
        ScoreBoardClock.getInstance().rewindTo(snapshot.getSnapshotTime());
        for (Clock clock : getAll(CLOCK)) { clock.restoreSnapshot(snapshot.getClockSnapshot(clock.getProviderId())); }
        set(IN_JAM, snapshot.inJam());
        set(IN_PERIOD, snapshot.inPeriod());
        set(CURRENT_PERIOD, snapshot.getCurrentPeriod());
        getCurrentPeriod().restoreSnapshot(snapshot.getPeriodSnapshot());
        if (getCurrentTimeout() != snapshot.getCurrentTimeout() && getCurrentTimeout() != noTimeoutDummy) {
            getCurrentTimeout().delete();
        }
        set(CURRENT_TIMEOUT, snapshot.getCurrentTimeout());
        getCurrentTimeout().set(Timeout.RUNNING, snapshot.inTimeout());
        set(OR_IS_TO, snapshot.orIsTo());
        set(IN_OVERTIME, snapshot.inOvertime());
        for (Team team : getAll(TEAM)) { team.restoreSnapshot(snapshot.getTeamSnapshot(team.getProviderId())); }
        for (BoxTrip bt : getAll(Team.BOX_TRIP)) { bt.restoreSnapshot(snapshot.getBoxTripSnapshot(bt.getId())); }
        for (Team team : getAll(TEAM)) {
            for (BoxTrip bt : team.getAll(Team.BOX_TRIP)) {
                bt.restoreSnapshot(snapshot.getBoxTripSnapshot(bt.getId()));
            }
        }
    } finally {
        restoreRunning = false;
    }
}
```

**File:** `src/com/carolinarollergirls/scoreboard/core/game/GameImpl.java`

## Version

- **Affected:** v2025.8, v2025.9
- **Not affected:** v2025.7 (flag did not exist in this version)

## Environment

- OS: Windows (scoreboard operator PC)
- Scoreboard version: v2025.9 (also reproduced on v2025.8)
- Reverted to v2025.7 as workaround

## Workaround

Downgrade to **v2025.7**, or fully restart the scoreboard application after
triggering the Undo to recover button functionality.

## Additional Context

- The `restoreRunning` flag was introduced specifically to prevent snapshot
  corruption during restore, which is a valid and necessary protection.
- The fix does not change the logic of the restore — only ensures the flag is
  always cleared via `finally`, which is standard Java practice for guard flags.
- The upstream commit that introduced the issue is `58904866` (merged into dev
  between v2025.7 and v2025.8).

### PR DESCRIPTION
**Pull request by frank-weinberg**
- avoid a race that could freeze the scoreboard on stats export
- Catch & Log exceptions in every thread

### CODE REVIEW

File: src/com/carolinarollergirls/scoreboard/core/game/GameImpl.java [hunk 1]
```diff
@@ -429,6 +429,7 @@ protected void valueChanged(Value<?> prop, Object value, Object last, Source sou
             }
             if (!"Never".equals(get(LAST_FILE_UPDATE))) { set(LAST_FILE_UPDATE, "Pre Game"); }
         }
+        if (prop == FILENAME && jsonSnapshotter != null) { jsonSnapshotter.setFilename((String) value); }
```
Comment (a1ly404) [inline src/com/carolinarollergirls/scoreboard/core/game/GameImpl.java:432]: @frank-weinberg so is this where the race condition could happen? If the jsonSnapshotter is null and we have a filename where a value is being changed? Do snapshots happen on every changed value?

Comment (frank-weinberg) [reply src/com/carolinarollergirls/scoreboard/core/game/GameImpl.java:432]: No. The race was:

Thread 1: 
- Export is triggered from UI
- WS.java l.162 calls runInBatch
- ScoreBoardEventProviderImpl l.118 acquires the coreLock
- some unrelated code runs

Meanwhile Thread 2: 
- regular data update for Game X triggered from JSONStateManger l.76 
- JSONStateSnapshotter l.37 calls synchronized method writeFile
- Thread gets the lock associated with the synchronized
- JSONStateSnapshotter l.47 called game.getFilename() -> this place was changed
- GameImpl l.1174 calls get
- ScoreBoardEventProviderImpl l.451 tries to acquire the coreLock and blocks because Thread 1 holds the lock

Thread 1:
- GameImpl l.534 calls jsonSnapshotter.writeFile and blocks because the method is synchronized and Thread 2 holds the lock.

And now both threads are blocked waiting for each other. And since one of them holds the coreLock, no other thread can perform any meaningful action.
